name: Build Executables

on:
  push:
    tags: ['v*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.12.3]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller
    
    - name: Build executable (Windows)
      if: runner.os == 'Windows'
      run: |
        # Use --onedir for better asset handling
        pyinstaller --onedir --add-data "assets;assets" --hidden-import pygame --hidden-import pygame.mixer --hidden-import pygame.font main.py
        # Create a zip file for distribution
        cd dist
        powershell Compress-Archive -Path "main" -DestinationPath "asteroids-windows.zip"
        cd ..
    
    - name: Build executable (Unix)
      if: runner.os != 'Windows'
      run: |
        pyinstaller --onedir --add-data "assets:assets" --hidden-import pygame --hidden-import pygame.mixer --hidden-import pygame.font main.py
        cd dist
        zip -r asteroids-unix.zip main
        cd ..
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: asteroids-${{ runner.os }}
        path: |
          dist/main.exe
          dist/main
          dist/asteroids-windows.zip
          dist/asteroids-unix.zip
          dist/
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Automated build for tag ${{ github.ref_name }}
          
          This release contains executables for:
          - Windows
          - Linux
          - macOS
          
          Built from commit: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 